# -*- coding: utf-8 -*-
"""DSP_Project_Plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqMPOMkJdEqa_ZcxtIknQlc8N0hgEL_S
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()  # upload both CSVs together

df_literacy = pd.read_csv('State-wise_literacy_rates_and_increase-in_literacy_rates_as_per_Census_during_2001_and_2011.csv')
df_ru = pd.read_csv('State_UT-wise_Rural_and_Urban_Population_as_Per_Census_during_2001_and_2011.csv')

print("Literacy CSV shape:", df_literacy.shape)
print(df_literacy.head(3))
print("\nRural Urban CSV shape:", df_ru.shape)
print(df_ru.head(3))

# ── Clean df_literacy ──────────────────────────────────────────────
# Drop India total row
df_literacy = df_literacy[df_literacy['S. No.'] != 'INDIA'].copy()

# Drop S.No column
df_literacy.drop(columns=['S. No.'], inplace=True)

# Rename columns
df_literacy.columns = [
    'State',
    'Lit_Total_2001', 'Lit_Total_2011',
    'Lit_Male_2001', 'Lit_Male_2011',
    'Lit_Female_2001', 'Lit_Female_2011',
    'Inc_Total', 'Inc_Male', 'Inc_Female'
]

df_literacy['State'] = df_literacy['State'].str.strip()
df_literacy = df_literacy.reset_index(drop=True)

print("Literacy cleaned shape:", df_literacy.shape)
print(df_literacy.head(3))

# ── Clean df_ru ────────────────────────────────────────────────────
# Drop Note column and S.No
df_ru.drop(columns=['S. No.', 'Note of State/ UT'], inplace=True)

# Remove All India total row
df_ru = df_ru[~df_ru['State/ UT'].str.contains('Total', na=False)].copy()

# Rename columns
df_ru.columns = [
    'State',
    'Rural_Pop_2001', 'Urban_Pop_2001', 'Total_Pop_2001', 'Rural_Pct_2001',
    'Rural_Pop_2011', 'Urban_Pop_2011', 'Total_Pop_2011', 'Rural_Pct_2011'
]

df_ru['Urban_Pct_2011'] = (100 - df_ru['Rural_Pct_2011']).round(2)
df_ru['Urban_Pct_2001'] = (100 - df_ru['Rural_Pct_2001']).round(2)
df_ru['State'] = df_ru['State'].str.strip()
df_ru = df_ru.reset_index(drop=True)

print("\nRural Urban cleaned shape:", df_ru.shape)
print(df_ru.head(3))

# Check what's in ru but not in literacy
print("In ru but not in literacy:",
      set(df_ru['State']) - set(df_literacy['State']))

print("In literacy but not in ru:",
      set(df_literacy['State']) - set(df_ru['State']))

# Fix state names in df_ru to match df_literacy
ru_fixes = {
    'A & N Island': 'Andaman & Nicobar Islands',
    'Uttarakhand': 'Uttrakhand',  # match literacy spelling
    'Telangana': 'Telangana'      # not in literacy, will be NaN after merge — expected
}

df_ru['State'] = df_ru['State'].replace(ru_fixes)

# Verify
print("Remaining mismatches:", set(df_ru['State']) - set(df_literacy['State']))

df_state = pd.merge(df_literacy, df_ru, on='State', how='outer')

print("df_state shape:", df_state.shape)
print("Missing values:\n", df_state.isnull().sum()[df_state.isnull().sum() > 0])
print(df_state.head(3))

"""**PLOTTING**"""

import plotly.express as px

# Sort by 2011 literacy rate
df_plot = df_state.dropna(subset=['Lit_Total_2011']).sort_values('Lit_Total_2011')

fig_lit_trend = px.bar(
    df_plot,
    x='State',
    y=['Lit_Total_2001', 'Lit_Total_2011'],
    barmode='group',
    title='Literacy Rate by State — 2001 vs 2011',
    labels={'value': 'Literacy Rate (%)', 'variable': 'Year'},
    color_discrete_map={
        'Lit_Total_2001': '#636EFA',
        'Lit_Total_2011': '#00CC96'
    }
)
fig_lit_trend.update_layout(
    height=500,
    xaxis_tickangle=-45,
    legend_title='Year'
)
fig_lit_trend.show()

df_improved = df_state.dropna(subset=['Inc_Total']).sort_values('Inc_Total', ascending=False)

fig_improved = px.bar(
    df_improved,
    x='Inc_Total',
    y='State',
    orientation='h',
    color='Inc_Total',
    color_continuous_scale='Viridis',
    title='Literacy Rate Increase by State — 2001 to 2011 (Percentage Points)',
    labels={'Inc_Total': 'Increase (pp)', 'State': ''}
)
fig_improved.update_layout(height=700)
fig_improved.show()

df_state['Gender_Gap_2011'] = (df_state['Lit_Male_2011'] - df_state['Lit_Female_2011']).round(2)
df_state['Gender_Gap_2001'] = (df_state['Lit_Male_2001'] - df_state['Lit_Female_2001']).round(2)

df_gap = df_state.dropna(subset=['Gender_Gap_2011']).sort_values('Gender_Gap_2011', ascending=False)

fig_gender_gap = px.bar(
    df_gap,
    x='Gender_Gap_2011',
    y='State',
    orientation='h',
    color='Gender_Gap_2011',
    color_continuous_scale='Reds',
    title='Male-Female Literacy Gap by State — 2011',
    labels={'Gender_Gap_2011': 'Gap (percentage points)', 'State': ''}
)
fig_gender_gap.update_layout(height=700)
fig_gender_gap.show()

"""**IN THE DISTRICT DATASET**"""

uploaded = files.upload()  # upload df_pivot.csv

df_pivot = pd.read_csv('df_pivot.csv')

print(df_pivot.shape)
print(df_pivot.columns.tolist())
print(df_pivot.head(3))


import json
with open('india_compressed.geojson') as f:
    compressed_geojson = json.load(f)

print("GeoJSON loaded:", len(compressed_geojson['features']), "features")

top10 = df_pivot.nlargest(10, 'Literacy_Rate')[['State', 'District_Name', 'Literacy_Rate']]
bot10 = df_pivot.nsmallest(10, 'Literacy_Rate')[['State', 'District_Name', 'Literacy_Rate']]

top10['Category'] = 'Top 10'
bot10['Category'] = 'Bottom 10'
combined = pd.concat([top10, bot10])

fig_top_bot = px.bar(
    combined,
    x='Literacy_Rate',
    y='District_Name',
    color='Category',
    orientation='h',
    color_discrete_map={'Top 10': '#00CC96', 'Bottom 10': '#EF553B'},
    title='Top 10 & Bottom 10 Districts by Literacy Rate - 2011',
    hover_data=['State', 'Literacy_Rate'],
    labels={'District_Name': '', 'Literacy_Rate': 'Literacy Rate (%)'}
)
fig_top_bot.update_layout(
    height=600,
    yaxis={'categoryorder': 'total ascending'}
)
fig_top_bot.show()

top10_sr = df_pivot.nlargest(10, 'Sex_Ratio')[['State', 'District_Name', 'Sex_Ratio']]
bot10_sr = df_pivot.nsmallest(10, 'Sex_Ratio')[['State', 'District_Name', 'Sex_Ratio']]

top10_sr['Category'] = 'Top 10'
bot10_sr['Category'] = 'Bottom 10'
combined_sr = pd.concat([top10_sr, bot10_sr])

fig_top_bot_sr = px.bar(
    combined_sr,
    x='Sex_Ratio',
    y='District_Name',
    color='Category',
    orientation='h',
    color_discrete_map={'Top 10': '#636EFA', 'Bottom 10': '#EF553B'},
    title='Top 10 & Bottom 10 Districts by Sex Ratio - 2011',
    hover_data=['State', 'Sex_Ratio'],
    labels={'District_Name': '', 'Sex_Ratio': 'Females per 1000 Males'}
)
fig_top_bot_sr.update_layout(
    height=600,
    yaxis={'categoryorder': 'total ascending'}
)
fig_top_bot_sr.show()

state_lit = df_pivot.groupby('State').agg(
    Rural_Lit=('Literacy_Rate_Rural', 'mean'),
    Urban_Lit=('Literacy_Rate_Urban', 'mean')
).reset_index().sort_values('Rural_Lit')

fig_ru_lit = px.bar(
    state_lit,
    x='State',
    y=['Rural_Lit', 'Urban_Lit'],
    barmode='group',
    title='Rural vs Urban Literacy Rate by State - 2011',
    labels={'value': 'Literacy Rate (%)', 'variable': 'Type'},
    color_discrete_map={'Rural_Lit': '#19D3F3', 'Urban_Lit': '#FF6692'}
)
fig_ru_lit.update_layout(
    height=500,
    xaxis_tickangle=-45
)
fig_ru_lit.show()

fig_scatter1 = px.scatter(
    df_pivot,
    x='Urban_Pct',
    y='Literacy_Rate',
    color='Total_Pop',                    # color by population size
    color_continuous_scale='Viridis',
    hover_data=['State', 'District_Name', 'Total_Pop'],
    title='Literacy Rate vs Urbanisation by District - 2011',
    labels={
        'Urban_Pct': 'Urban Population (%)',
        'Literacy_Rate': 'Literacy Rate (%)',
        'Total_Pop': 'Total Population'
    },
    opacity=0.7,
    size='Total_Pop',                     # bubble size = population
    size_max=40
)
fig_scatter1.update_layout(height=600)
fig_scatter1.show()

fig_scatter1 = px.scatter(
    df_pivot,
    x='Urban_Pct',
    y='Literacy_Rate',
    color='Total_Pop',
    color_continuous_scale='Viridis',
    hover_data=['State', 'District_Name', 'Total_Pop'],
    title='Literacy Rate vs Urbanisation by District - 2011',
    labels={
        'Urban_Pct': 'Urban Population (%)',
        'Literacy_Rate': 'Literacy Rate (%)',
        'Total_Pop': 'Total Population'
    },
    opacity=0.7
)
fig_scatter1.update_traces(marker=dict(size=7))
fig_scatter1.update_layout(height=600)
fig_scatter1.show()

fig_scatter2 = px.scatter(
    df_pivot,
    x='Literacy_Rate',
    y='Sex_Ratio',
    color='Urban_Pct',                    # color by urbanisation level
    color_continuous_scale='RdYlGn',
    hover_data=['State', 'District_Name', 'Total_Pop'],
    title='Sex Ratio vs Literacy Rate by District - 2011',
    labels={
        'Literacy_Rate': 'Literacy Rate (%)',
        'Sex_Ratio': 'Females per 1000 Males',
        'Urban_Pct': 'Urban %'
    },
    opacity=0.7
)
fig_scatter2.update_layout(height=600)
fig_scatter2.show()

fig_scatter2.update_traces(marker=dict(size=8))  # increase from default ~5

fig_hist = px.histogram(
    df_pivot,
    x='Literacy_Rate',
    nbins=30,
    color_discrete_sequence=['#636EFA'],
    title='Distribution of Literacy Rate across Districts - 2011',
    labels={'Literacy_Rate': 'Literacy Rate (%)', 'count': 'Number of Districts'}
)
fig_hist.update_layout(height=400, bargap=0.1)
fig_hist.show()

df_urb = df_state.dropna(subset=['Urban_Pct_2011']).sort_values('Urban_Pct_2011')

fig_urb = px.bar(
    df_urb,
    x='State',
    y=['Urban_Pct_2001', 'Urban_Pct_2011'],
    barmode='group',
    title='Urbanisation Rate by State — 2001 vs 2011',
    labels={'value': 'Urban Population (%)', 'variable': 'Year'},
    color_discrete_map={
        'Urban_Pct_2001': '#FFA15A',
        'Urban_Pct_2011': '#AB63FA'
    }
)
fig_urb.update_layout(height=500, xaxis_tickangle=-45)
fig_urb.show()

# Calculate population growth percentage
df_state['Pop_Growth_Pct'] = ((df_state['Total_Pop_2011'] - df_state['Total_Pop_2001']) / df_state['Total_Pop_2001']) * 100

# Remove Andhra Pradesh from growth chart as boundary changed
df_growth = df_state.dropna(subset=['Pop_Growth_Pct'])
df_growth = df_growth[df_growth['State'] != 'Andhra Pradesh']
df_growth = df_growth.sort_values('Pop_Growth_Pct', ascending=False)

fig_growth = px.bar(
    df_growth,
    x='Pop_Growth_Pct',
    y='State',
    orientation='h',
    color='Pop_Growth_Pct',
    color_continuous_scale='RdYlGn',
    title='Population Growth Rate by State — 2001 to 2011 (%) [Andhra Pradesh excluded due to boundary change]',
    labels={'Pop_Growth_Pct': 'Growth (%)', 'State': ''}
)
fig_growth.update_layout(height=700)
fig_growth.show()

import geopandas as gpd
import matplotlib.pyplot as plt
import json

# Load compressed geojson
gdf = gpd.read_file('india_compressed.geojson')

# Fix invalid geometries first
gdf['geometry'] = gdf['geometry'].buffer(0)

# Now dissolve
india_boundary = gdf.dissolve()

# Quick plot to check
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Left — all districts
gdf.plot(ax=axes[0], color='lightblue', edgecolor='grey', linewidth=0.3)
axes[0].set_title('All Districts')
axes[0].axis('off')

# Right — dissolved boundary only
india_boundary.plot(ax=axes[1], color='none', edgecolor='black', linewidth=1.5)
axes[1].set_title('India Outer Boundary')
axes[1].axis('off')

plt.tight_layout()
plt.show()

# Check how many districts matched between df_pivot and geojson
geojson_ids = set(str(f['properties']['pc11_d_id']) for f in compressed_geojson['features']
                   if f['properties']['pc11_d_id'] is not None)

df_ids = set(df_pivot['pc11_d_id'].astype(str))

print("GeoJSON IDs count:", len(geojson_ids))
print("df_pivot IDs count:", len(df_ids))
print("In GeoJSON but not in df:", geojson_ids - df_ids)
print("In df but not in GeoJSON:", df_ids - geojson_ids)

# Convert pc11_d_id in df_pivot to zero-padded 3-digit string
df_pivot['pc11_d_id'] = df_pivot['pc11_d_id'].astype(int).apply(lambda x: str(x).zfill(3))

# Verify
print("Sample pc11_d_id from df:", df_pivot['pc11_d_id'].head(5).tolist())

# Check mismatches again
geojson_ids = set(str(f['properties']['pc11_d_id']) for f in compressed_geojson['features']
                   if f['properties']['pc11_d_id'] is not None)
df_ids = set(df_pivot['pc11_d_id'])

print("Remaining mismatches:", df_ids - geojson_ids)
print("Matched count:", len(df_ids & geojson_ids))

fig = px.choropleth_mapbox(
    df_pivot,
    geojson=compressed_geojson,
    featureidkey='properties.pc11_d_id',
    locations='pc11_d_id',
    color='Literacy_Rate',
    color_continuous_scale='Viridis',
    range_color=[30, 100],
    title='Literacy Rate by District - Census 2011',
    hover_data=['State', 'District_Name', 'Total_Pop', 'Literacy_Rate'],
    mapbox_style='carto-positron',
    center={"lat": 20.5937, "lon": 78.9629},
    zoom=3.5,
    opacity=0.7
)
fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=600
)
fig.show()

import plotly.graph_objects as go

fig = px.choropleth_mapbox(
    df_pivot,
    geojson=compressed_geojson,
    featureidkey='properties.pc11_d_id',
    locations='pc11_d_id',
    color='Literacy_Rate',
    color_continuous_scale='Viridis',
    range_color=[30, 100],
    title='Literacy Rate by District - Census 2011',
    hover_data=['State', 'District_Name', 'Total_Pop', 'Literacy_Rate'],
    mapbox_style='carto-positron',
    center={"lat": 20.5937, "lon": 78.9629},
    zoom=3.5,
    opacity=0.7
)

# Add India outer boundary
boundary_geom = india_boundary.geometry.iloc[0]

if boundary_geom.geom_type == 'MultiPolygon':
    lons, lats = [], []
    for poly in boundary_geom.geoms:
        coords = list(poly.exterior.coords)
        lons += [c[0] for c in coords] + [None]
        lats += [c[1] for c in coords] + [None]
else:
    coords = list(boundary_geom.exterior.coords)
    lons = [c[0] for c in coords]
    lats = [c[1] for c in coords]

fig.add_trace(go.Scattermapbox(
    lon=lons,
    lat=lats,
    mode='lines',
    line=dict(color='black', width=0.5),
    hoverinfo='skip',
    showlegend=False
))

fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=700
)
fig.show()

fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=900,
    mapbox=dict(
        style='white-bg'
    )
)