# -*- coding: utf-8 -*-
"""DSP_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKpktAlI71YcKYQNDDy_5DlfDnhRGuPZ
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()  # upload here

df_district_raw = pd.read_excel('2011-IndiaStateDist-0000.xlsx', sheet_name='Data')

df_district_raw

# 1. Filter district-level only
df_district = df_district_raw[df_district_raw['Level'] == 'DISTRICT']

# 2. Keep only the columns you need (from the record structure image)
cols_to_keep = ['State', 'District', 'Name', 'TRU',
                'TOT_P', 'TOT_M', 'TOT_F',
                'P_06', 'M_06', 'F_06',
                'P_SC', 'M_SC', 'F_SC',
                'P_ST', 'M_ST', 'F_ST',
                'P_LIT', 'M_LIT', 'F_LIT',
                'P_ILL', 'M_ILL', 'F_ILL',
                'TOT_WORK_P', 'TOT_WORK_M', 'TOT_WORK_F']

df_district = df_district[cols_to_keep]

# 3. Pivot — spread Total/Rural/Urban into columns
df_pivot = df_district.pivot_table(
    index=['State', 'District', 'Name'],
    columns='TRU',
    values=['TOT_P', 'TOT_M', 'TOT_F',
            'P_LIT', 'M_LIT', 'F_LIT',
            'P_ILL', 'M_ILL', 'F_ILL'
            ]
)

# 4. Flatten the multi-level column names
df_pivot.columns = ['_'.join(col).strip() for col in df_pivot.columns]
# This gives you columns like TOT_P_Total, TOT_P_Rural, TOT_P_Urban etc.

# 5. Reset index
df_pivot = df_pivot.reset_index()

# 6. Rename for clarity
df_pivot.rename(columns={
    'Name': 'District_Name',
    'TOT_P_Total': 'Total_Pop',
    'TOT_M_Total': 'Male_Pop',
    'TOT_F_Total': 'Female_Pop',
    'TOT_P_Rural': 'Rural_Pop',
    'TOT_P_Urban': 'Urban_Pop',
    'P_LIT_Total': 'Literate_Pop',
    'P_06_Total':  'Pop_Under6',
    # add more as needed
}, inplace=True)

print(df_pivot.shape)  # should be ~640 rows, 1 row per district
df_pivot.head()

df_pivot

print(df_pivot.columns.tolist())

ordered_cols = [
    'State', 'District', 'District_Name',

    # Total
    'Total_Pop', 'Male_Pop', 'Female_Pop',
    'Literate_Pop', 'M_LIT_Total', 'F_LIT_Total',
    'P_ILL_Total', 'M_ILL_Total', 'F_ILL_Total',

    # Rural
    'Rural_Pop', 'TOT_M_Rural', 'TOT_F_Rural',
    'P_LIT_Rural', 'M_LIT_Rural', 'F_LIT_Rural',
    'P_ILL_Rural', 'M_ILL_Rural', 'F_ILL_Rural',

    # Urban
    'Urban_Pop', 'TOT_M_Urban', 'TOT_F_Urban',
    'P_LIT_Urban', 'M_LIT_Urban', 'F_LIT_Urban',
    'P_ILL_Urban', 'M_ILL_Urban', 'F_ILL_Urban',
]

df_pivot = df_pivot[ordered_cols]
df_pivot.head()

df_pivot

# Get the state code to name mapping from the original data before you filtered it
state_mapping = df_district_raw[
    (df_district_raw['Level'] == 'STATE') &
    (df_district_raw['TRU'] == 'Total')
][['State', 'Name']].drop_duplicates()

# state_mapping looks like:  State=1, Name='Jammu & Kashmir' etc.

# Merge into your pivot dataframe
df_pivot = df_pivot.merge(state_mapping, on='State', how='left')

# Replace the State column with the name
df_pivot.drop(columns=['State'], inplace=True)
df_pivot.rename(columns={'Name': 'State'}, inplace=True)

# Move State to the front
cols = ['State', 'District', 'District_Name'] + [c for c in df_pivot.columns if c not in ['State', 'District', 'District_Name']]
df_pivot = df_pivot[cols]

df_pivot

"""**CREATING CHOROPLETH**"""

# List of districts that became Telangana in 2014
telangana_districts = [
    'Adilabad', 'Nizamabad', 'Karimnagar', 'Medak', 'Hyderabad',
    'Rangareddy', 'Mahbubnagar', 'Nalgonda', 'Warangal', 'Khammam'
]

print(df_pivot[df_pivot['State'] == 'ANDHRA PRADESH']['District_Name'].tolist())

# In df_pivot, reassign those districts' state to Telangana
df_pivot['State'] = df_pivot.apply(
    lambda row: 'Telangana'
    if row['District_Name'] in telangana_districts
    else row['State'],
    axis=1
)

# Verify
print(df_pivot[df_pivot['State'] == 'Telangana']['District_Name'].tolist())
print(df_pivot[df_pivot['State'] == 'ANDHRA PRADESH']['District_Name'].tolist())

df_pivot

# Step 1 — Aggregate df_pivot to state level
df_state_agg = df_pivot.groupby('State').agg(
    Total_Pop=('Total_Pop', 'sum'),
    Male_Pop=('Male_Pop', 'sum'),
    Female_Pop=('Female_Pop', 'sum'),
    Literate_Pop=('Literate_Pop', 'sum'),
).reset_index()

# Step 2 — Derive literacy rate
df_state_agg['Literacy_Rate'] = (df_state_agg['Literate_Pop'] / df_state_agg['Total_Pop'] * 100).round(2)
df_state_agg['Sex_Ratio'] = (df_state_agg['Female_Pop'] / df_state_agg['Male_Pop'] * 1000).round(1)

# Step 3 — Load GeoJSON
import requests
import plotly.express as px

geojson_url = "https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson"
india_geojson = requests.get(geojson_url).json()

# Step 4 — Check name mismatches first!
geojson_states = [f['properties']['ST_NM'] for f in india_geojson['features']]
print("In GeoJSON but not in df:", set(geojson_states) - set(df_state_agg['State']))
print("In df but not in GeoJSON:", set(df_state_agg['State']) - set(geojson_states))

import requests

geojson_url = "https://raw.githubusercontent.com/geohacker/india/master/state/india_telengana.geojson"
india_geojson = requests.get(geojson_url).json()

# Check what property key holds the state name
print(india_geojson['features'][0]['properties'])

# First check what the key is called from Cell 1 output
# It's usually 'NAME_1' or 'ST_NM' or 'STATE'

for f in india_geojson['features']:
    print(f['properties'])  # print all properties to find the right key

geojson_states = [f['properties']['NAME_1'] for f in india_geojson['features']]

print("GeoJSON state count:", len(geojson_states))
print("Your df state count:", len(df_state_agg['State'].tolist()))

print("\nGeoJSON states:", sorted(geojson_states))
print("\nYour df states:", sorted(df_state_agg['State'].tolist()))

print("\nIn GeoJSON but not in df:", set(geojson_states) - set(df_state_agg['State']))
print("In df but not in GeoJSON:", set(df_state_agg['State']) - set(geojson_states))

# Step 1 — Convert df to Title Case first
df_state_agg['State'] = df_state_agg['State'].str.title()

# Step 2 — Fix specific mismatches
name_fixes = {
    # Caps/spelling differences
    'Andaman & Nicobar Islands': 'Andaman and Nicobar',
    'Dadra & Nagar Haveli': 'Dadra and Nagar Haveli',
    'Daman & Diu': 'Daman and Diu',
    'Jammu & Kashmir': 'Jammu and Kashmir',
    'Nct Of Delhi': 'Delhi',
    'Odisha': 'Orissa',          # GeoJSON uses old name Orissa
    'Uttarakhand': 'Uttaranchal', # GeoJSON uses old name Uttaranchal
}

df_state_agg['State'] = df_state_agg['State'].replace(name_fixes)

# Step 3 — Verify
geojson_states = [f['properties']['NAME_1'] for f in india_geojson['features']]
print("Remaining mismatches:", set(df_state_agg['State']) - set(geojson_states))
# Should print empty set()

geojson_url = "https://raw.githubusercontent.com/geohacker/india/master/district/india_district.geojson"
response = requests.get(geojson_url)
print(response.status_code)
print(response.text[:500])

india_district_geojson = response.json()

# Check properties
print(india_district_geojson['features'][0]['properties'])

# Count
print("GeoJSON district count:", len(india_district_geojson['features']))

for f in india_district_geojson['features']:
    print(f['properties'])  # print all properties to find the right key

geojson_districts = [f['properties']['NAME_2'] for f in india_district_geojson['features']]

print("GeoJSON district count:", len(geojson_districts))
print("Your df district count:", len(df_pivot['District_Name'].tolist()))

print("\nIn GeoJSON but not in df:", set(geojson_districts) - set(df_pivot['District_Name']))
print("\nIn df but not in GeoJSON:", set(df_pivot['District_Name']) - set(geojson_districts))

df_pivot['District_Name'] = df_pivot['District_Name'].str.strip()

district_fixes = {
    # Name differences
    'Khandwa (East Nimar)': 'East Nimar',
    'Khargone (West Nimar)': 'West Nimar',
    'Kanshiram Nagar': 'Kansiram Nagar',
    'Morigaon': 'Marigaon',
    'Siddharthnagar': 'Siddharth Nagar',
    'Baudh': 'Bauda',
    'Leh(Ladakh)': 'Leh (ladakh)',
    'Lawngtlai': 'Lawangtlai',
    'Virudhunagar': 'Virudunagar',
    'Chamarajanagar': 'Chamrajnagar',
    'Mahrajganj': 'Maharajganj',
    'Gadchiroli': 'Garhchiroli',
    'Ribhoi': 'Ri Bhoi',
    'Saran': 'Saran (chhapra)',
    'Y.S.R.': 'Y.s.r.',
    'Sant Ravidas Nagar (Bhadohi)': 'Sant Ravi Das Nagar(bhadohi)',
    'Saraikela-Kharsawan': 'Saraikela-kharsawan',
    'Nicobars': 'Nicobar',
    'South Twenty Four Parganas': 'South 24 Parganas',
    'North Twenty Four Parganas': 'North 24 Parganas',
    # Sikkim districts
    'North  District': 'North',
    'East District': 'East',
    'West District': 'West',
    'South District': 'South',
    # Andaman
    'North  & Middle Andaman': 'North & Middle Andaman',
}

df_pivot['District_Name'] = df_pivot['District_Name'].replace(district_fixes)

geojson_districts = [f['properties']['DISTRICT'] for f in india_district_geojson['features']]
remaining = set(df_pivot['District_Name']) - set(geojson_districts)
print("Remaining mismatches:", remaining)
# Should print empty set()

district_fixes_2 = {
    'Kaimur (Bhabua)': 'Kaimur (bhabua)',
    'Janjgir - Champa': 'Janjgir-champa',
    'Paschim Medinipur': 'Pashchim Medinipur',
    'Nagapattinam': 'Nagappattinam',
}

df_pivot['District_Name'] = df_pivot['District_Name'].replace(district_fixes_2)

# Verify
geojson_districts = [f['properties']['DISTRICT'] for f in india_district_geojson['features']]
remaining = set(df_pivot['District_Name']) - set(geojson_districts)
print("Remaining mismatches:", remaining)
# Should print empty set()

import plotly.express as px

fig = px.choropleth_mapbox(
    df_pivot,
    geojson=india_district_geojson,
    featureidkey='properties.DISTRICT',
    locations='District_Name',
    color='F_LIT_Rural',
    color_continuous_scale='Viridis',
    title='Literate Population by District - Census 2011',
    hover_data=['State', 'District_Name', 'Total_Pop', 'Literate_Pop'],
    mapbox_style='carto-positron',  # base map style
    center={"lat": 20.5937, "lon": 78.9629},  # center of India
    zoom=3.5,
    opacity=0.7
)

fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=600
)


fig.show()

# Check how many districts didn't match
geojson_districts = [f['properties']['DISTRICT'] for f in india_district_geojson['features']]
matched = df_pivot[df_pivot['District_Name'].isin(geojson_districts)]
print(f"Matched: {len(matched)} / {len(df_pivot)}")
print(f"Unmatched: {len(df_pivot) - len(matched)}")

# Add literacy rate column
df_pivot['Literacy_Rate'] = (df_pivot['Literate_Pop'] / df_pivot['Total_Pop'] * 100).round(2)

fig = px.choropleth_mapbox(
    df_pivot,
    geojson=india_district_geojson,
    featureidkey='properties.DISTRICT',
    locations='District_Name',
    color='Literacy_Rate',
    color_continuous_scale='Viridis',
    range_color=[30, 100],          # set min/max range for better contrast
    title='Literacy Rate by District - Census 2011',
    hover_data=['State', 'District_Name', 'Total_Pop', 'Literacy_Rate'],
    mapbox_style='carto-positron',
    center={"lat": 20.5937, "lon": 78.9629},
    zoom=3.5,
    opacity=0.7
)

fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=600
)

fig.show()

# Literacy rates
df_pivot['Literacy_Rate'] = (df_pivot['Literate_Pop'] / df_pivot['Total_Pop'] * 100).round(2)
df_pivot['Literacy_Rate_Rural'] = (df_pivot['P_LIT_Rural'] / df_pivot['Rural_Pop'] * 100).round(2)
df_pivot['Literacy_Rate_Urban'] = (df_pivot['P_LIT_Urban'] / df_pivot['Urban_Pop'] * 100).round(2)
df_pivot['Literacy_Gap'] = (df_pivot['Literacy_Rate_Urban'] - df_pivot['Literacy_Rate_Rural']).round(2)

# Urbanisation
df_pivot['Urban_Pct'] = (df_pivot['Urban_Pop'] / df_pivot['Total_Pop'] * 100).round(2)
df_pivot['Rural_Pct'] = (df_pivot['Rural_Pop'] / df_pivot['Total_Pop'] * 100).round(2)

# Sex ratio (females per 1000 males)
df_pivot['Sex_Ratio'] = (df_pivot['Female_Pop'] / df_pivot['Male_Pop'] * 1000).round(1)

# Verify
print(df_pivot[['District_Name', 'Literacy_Rate', 'Literacy_Rate_Rural',
                 'Literacy_Rate_Urban', 'Literacy_Gap',
                 'Urban_Pct', 'Sex_Ratio']].head())

df_pivot

# Save to CSV
df_pivot.to_csv('india_census_2011_cleaned.csv', index=False)

files.download('india_census_2011_cleaned.csv')

# Fill NaN with 0 for districts that are fully urban or fully rural
df_pivot['Literacy_Rate_Rural'] = df_pivot['Literacy_Rate_Rural'].fillna(0)
df_pivot['Literacy_Rate_Urban'] = df_pivot['Literacy_Rate_Urban'].fillna(0)
df_pivot['Literacy_Gap'] = df_pivot['Literacy_Gap'].fillna(0)

# Check no NaNs remain in key columns
print(df_pivot[['Literacy_Rate', 'Literacy_Rate_Rural',
                 'Literacy_Rate_Urban', 'Literacy_Gap',
                 'Urban_Pct', 'Sex_Ratio']].isnull().sum())

df_pivot

# Plot all indicators separately, just change the col variable
col = 'Urban_Pct'  # change this to switch indicators

fig = px.choropleth_mapbox(
    df_pivot,
    geojson=india_district_geojson,
    featureidkey='properties.DISTRICT',
    locations='District_Name',
    color=col,
    color_continuous_scale='Viridis',
    title=f'{col} by District - Census 2011',
    hover_data=['State', 'District_Name', 'Total_Pop', col],
    mapbox_style='carto-positron',
    center={"lat": 20.5937, "lon": 78.9629},
    zoom=3.5,
    opacity=0.7
)
fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=600
)
fig.show()

# The GeoJSON has censuscode, your df has District column (numeric code)
# Add censuscode to your df_pivot for exact matching

# Check your df_pivot — does it have the District numeric code?
print(df_pivot[['State', 'District', 'District_Name']].head(10))

# Check GeoJSON censuscode
print(india_district_geojson['features'][0]['properties'])

# Strip all whitespace from District_Name
df_pivot['District_Name'] = df_pivot['District_Name'].str.strip()

# Also clean State column
df_pivot['State'] = df_pivot['State'].str.strip()

# Verify no whitespace remains
print("Districts with spaces:", df_pivot['District_Name'].str.contains('  ').sum())

# Check the census code matching
print("\ndf_pivot District column sample:")
print(df_pivot[['State', 'District', 'District_Name']].head(10))

print("\nGeoJSON censuscode sample:")
for f in india_district_geojson['features'][:5]:
    print(f['properties']['censuscode'], '-', f['properties']['DISTRICT'], '-', f['properties']['ST_NM'])

# Check if your df has State code as number
print(df_pivot['State'].unique())

# You need the numeric state code
# Go back to original raw data
print(df_district_raw[['State', 'District', 'Name', 'Level']].head(10))

# Build a lookup: (ST_CEN_CD, DT_CEN_CD) -> censuscode
geojson_lookup = {}
for f in india_district_geojson['features']:
    props = f['properties']
    key = (props['ST_CEN_CD'], props['DT_CEN_CD'])
    geojson_lookup[key] = props['censuscode']

print("Sample lookup:", list(geojson_lookup.items())[:5])

# Now get numeric state codes from raw data
state_code_map = df_district_raw[
    (df_district_raw['Level'] == 'STATE') &
    (df_district_raw['TRU'] == 'Total')
][['State', 'Name']].drop_duplicates()

print("\nState code map sample:")
print(state_code_map.head())

# Get numeric state code map
state_num_map = df_district_raw[
    (df_district_raw['Level'] == 'STATE') &
    (df_district_raw['TRU'] == 'Total')
][['State', 'Name']].drop_duplicates().set_index('Name')['State'].to_dict()

# Map state name to numeric code in df_pivot
df_pivot['State_Code'] = df_pivot['State'].map(state_num_map)

# Check how many mapped successfully
print("Missing State_Codes:", df_pivot['State_Code'].isnull().sum())
print(df_pivot[['State', 'State_Code']].drop_duplicates())

# Telangana uses state code 28 in the GeoJSON (carved out of Andhra Pradesh)
# Check what code GeoJSON uses for Telangana districts
for f in india_district_geojson['features']:
    if f['properties']['ST_NM'] == 'Andhra Pradesh':
        print(f['properties'])
        break

# Assign state code 28 to Telangana (same as AP in GeoJSON)
df_pivot.loc[df_pivot['State'] == 'Telangana', 'State_Code'] = 28

# Verify
print("Missing State_Codes after fix:", df_pivot['State_Code'].isnull().sum())

df_pivot['State_Code'] = df_pivot['State_Code'].astype(int)

df_pivot['censuscode'] = df_pivot.apply(
    lambda row: geojson_lookup.get((row['State_Code'], row['District']), None),
    axis=1
)

print("Missing censuscodes:", df_pivot['censuscode'].isnull().sum())
print(df_pivot[['State', 'District', 'District_Name', 'censuscode']].head(10))

print(df_pivot.shape)  # probably 1920 rows
print(df_pivot['District_Name'].nunique())  # should be 640

df_pivot

from google.colab import files
uploaded = files.upload()  # upload india_census_2011_official.geojson

import json
with open('india_census_2011_official.geojson') as f:
    official_geojson = json.load(f)

print("Total features:", len(official_geojson['features']))
print(official_geojson['features'][0]['properties'])

# Get numeric state code from raw data
state_num_map = df_district_raw[
    (df_district_raw['Level'] == 'STATE') &
    (df_district_raw['TRU'] == 'Total')
][['State', 'Name']].drop_duplicates().set_index('Name')['State'].to_dict()

# Map to df_pivot
df_pivot['State_Code'] = df_pivot['State'].map(state_num_map)

# Fix Telangana manually
df_pivot.loc[df_pivot['State'] == 'Telangana', 'State_Code'] = 28

# Convert to int
df_pivot['State_Code'] = df_pivot['State_Code'].astype(int)

# Verify
print("Missing State_Codes:", df_pivot['State_Code'].isnull().sum())
print(df_pivot[['State', 'State_Code', 'District', 'District_Name']].head())

# Check a known district - Gujarat Kachchh
print("Your df - Kachchh:")
print(df_pivot[df_pivot['District_Name'] == 'Kachchh'][['State_Code', 'District', 'District_Name']])

# Official GeoJSON - Kachchh
for f in official_geojson['features']:
    if f['properties']['d_name'] == 'Kachchh':
        print("\nOfficial GeoJSON - Kachchh:")
        print(f['properties'])

# Add all derived columns
df_pivot['Literacy_Rate'] = (df_pivot['Literate_Pop'] / df_pivot['Total_Pop'] * 100).round(2)
df_pivot['Literacy_Rate_Rural'] = (df_pivot['P_LIT_Rural'] / df_pivot['Rural_Pop'] * 100).round(2)
df_pivot['Literacy_Rate_Urban'] = (df_pivot['P_LIT_Urban'] / df_pivot['Urban_Pop'] * 100).round(2)
df_pivot['Literacy_Gap'] = (df_pivot['Literacy_Rate_Urban'] - df_pivot['Literacy_Rate_Rural']).round(2)
df_pivot['Urban_Pct'] = (df_pivot['Urban_Pop'] / df_pivot['Total_Pop'] * 100).round(2)
df_pivot['Rural_Pct'] = (df_pivot['Rural_Pop'] / df_pivot['Total_Pop'] * 100).round(2)
df_pivot['Sex_Ratio'] = (df_pivot['Female_Pop'] / df_pivot['Male_Pop'] * 1000).round(1)

# Fill NaN
df_pivot['Literacy_Rate_Rural'] = df_pivot['Literacy_Rate_Rural'].fillna(0)
df_pivot['Literacy_Rate_Urban'] = df_pivot['Literacy_Rate_Urban'].fillna(0)
df_pivot['Literacy_Gap'] = df_pivot['Literacy_Gap'].fillna(0)

print(df_pivot.columns.tolist())

# Step 2 - Convert District to string for GeoJSON matching
df_pivot['District_str'] = df_pivot['District'].astype(str)

# Step 3 - Plot
fig = px.choropleth_mapbox(
    df_pivot,
    geojson=official_geojson,
    featureidkey='properties.pc11_d_id',
    locations='District_str',              # use string version
    color='Literacy_Rate',
    color_continuous_scale='Viridis',
    range_color=[30, 100],
    title='Literacy Rate by District - Census 2011',
    hover_data=['State', 'District_Name', 'Total_Pop', 'Literacy_Rate'],
    mapbox_style='carto-positron',
    center={"lat": 20.5937, "lon": 78.9629},
    zoom=3.5,
    opacity=0.7
)
fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=600
)
fig.show()

# Install topojson for simplification
!pip install topojson

import topojson
import json

# Load your large geojson
with open('/content/india_census_2011_official.geojson') as f:  # use actual filename
    large_geojson = json.load(f)

print("Original features:", len(large_geojson['features']))
print("Original properties sample:", large_geojson['features'][0]['properties'])

for f in large_geojson['features']:
    print(f['properties'])  # print all properties to find the right key

# Build lookup from the new official GeoJSON
# key = (state_code, district_local_code), value = pc11_d_id (national code)
new_geojson_lookup = {}
for f in large_geojson['features']:
    props = f['properties']
    if props['pc11_s_id'] and props['pc11_d_id'] and props['pc11_d_id'] != '000':
        s_id = int(props['pc11_s_id'])
        d_id = int(props['pc11_d_id'])
        new_geojson_lookup[(s_id, d_id)] = d_id

print("Lookup size:", len(new_geojson_lookup))
print("Sample:", list(new_geojson_lookup.items())[:5])

print(df_pivot.columns)

df_pivot

# Build set of district names from official GeoJSON
geojson_d_names = set(f['properties']['d_name'] for f in large_geojson['features']
                       if f['properties']['d_name'] is not None)

# Compare with df_pivot
df_names = set(df_pivot['District_Name'].str.strip())

print("GeoJSON district count:", len(geojson_d_names))
print("df_pivot district count:", len(df_names))

print("\nIn GeoJSON but not in df:", geojson_d_names - df_names)
print("\nIn df but not in GeoJSON:", df_names - geojson_d_names)

# Fix Sikkim districts separately (filter by state)
sikkim_fixes = {
    'North': 'North  District',
    'West': 'West District',
    'South': 'South District',
    'East': 'East District',
}

for old, new in sikkim_fixes.items():
    df_pivot.loc[
        (df_pivot['State'] == 'SIKKIM') & (df_pivot['District_Name'] == old),
        'District_Name'
    ] = new

# Verify Sikkim
print("Sikkim districts:", df_pivot[df_pivot['State'] == 'SIKKIM']['District_Name'].tolist())

# Also verify Delhi is untouched
print("Delhi districts:", df_pivot[df_pivot['State'] == 'NCT OF DELHI']['District_Name'].tolist())

name_fixes = {
    'Leh (ladakh)': 'Leh(Ladakh)',
    'Kaimur (bhabua)': 'Kaimur (Bhabua)',
    'Ri Bhoi': 'Ribhoi',
    'Siddharth Nagar': 'Siddharthnagar',
    'Garhchiroli': 'Gadchiroli',
    'Sant Ravi Das Nagar(bhadohi)': 'Sant Ravidas Nagar (Bhadohi)',
    'Saraikela-kharsawan': 'Saraikela-Kharsawan',
    'Lawangtlai': 'Lawngtlai',
    'Chamrajnagar': 'Chamarajanagar',
    'Saran (chhapra)': 'Saran',
    'Y.s.r.': 'Y.S.R.',
    'Nagappattinam': 'Nagapattinam',
    'North & Middle Andaman': 'North  & Middle Andaman',
    'Marigaon': 'Morigaon',
    'Bauda': 'Baudh',
    'South 24 Parganas': 'South Twenty Four Parganas',
    'North 24 Parganas': 'North Twenty Four Parganas',
    'Pashchim Medinipur': 'Paschim Medinipur',
    'Janjgir-champa': 'Janjgir - Champa',
    'Kansiram Nagar': 'Kanshiram Nagar',
    'Virudunagar': 'Virudhunagar',
    'West Nimar': 'Khargone (West Nimar)',
    'East Nimar': 'Khandwa (East Nimar)',
    'Maharajganj': 'Mahrajganj',
    'Nicobar': 'Nicobars',
}

df_pivot['District_Name'] = df_pivot['District_Name'].replace(name_fixes)

# Verify
df_names = set(df_pivot['District_Name'].str.strip())
geojson_d_names = set(f['properties']['d_name'] for f in large_geojson['features']
                       if f['properties']['d_name'] is not None)


print("Remaining mismatches in df not in GeoJSON:", df_names - geojson_d_names)
print("Remaining mismatches in GeoJSON not in df:", geojson_d_names - df_names)

print("GeoJSON district count:", len(geojson_d_names))
print("df_pivot district count:", len(df_names))

df_pivot

# Build lookup: d_name -> pc11_d_id from official GeoJSON
name_to_pc11 = {}
for f in large_geojson['features']:
    props = f['properties']
    if props['d_name'] is not None:
        name_to_pc11[props['d_name']] = props['pc11_d_id']

# Map to df_pivot
df_pivot['pc11_d_id'] = df_pivot['District_Name'].map(name_to_pc11)

print("Missing pc11_d_id:", df_pivot['pc11_d_id'].isnull().sum())
print(df_pivot[['State', 'District_Name', 'pc11_d_id']].head(10))

fig = px.choropleth_mapbox(
    df_pivot,
    geojson=large_geojson,
    featureidkey='properties.pc11_d_id',
    locations='pc11_d_id',
    color='Literacy_Rate',
    color_continuous_scale='Viridis',
    range_color=[30, 100],
    title='Literacy Rate by District - Census 2011',
    hover_data=['State', 'District_Name', 'Total_Pop', 'Literacy_Rate'],
    mapbox_style='carto-positron',
    center={"lat": 20.5937, "lon": 78.9629},
    zoom=3.5,
    opacity=0.7
)
fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=600
)
fig.show()

# See which 6 are missing
print("Total rows:", len(df_pivot))

# Check Delhi districts specifically
print("\nDelhi districts and their pc11_d_id:")
print(df_pivot[df_pivot['State'] == 'NCT OF DELHI'][['District_Name', 'pc11_d_id']])

# Check Sikkim
print("\nSikkim districts and their pc11_d_id:")
print(df_pivot[df_pivot['State'] == 'SIKKIM'][['District_Name', 'pc11_d_id']])

# Check which rows have null pc11_d_id
print("\nRows with null pc11_d_id:")
print(df_pivot[df_pivot['pc11_d_id'].isnull()][['State', 'District_Name']])

print("df_pivot rows:", len(df_pivot))
print("Unique pc11_d_id:", df_pivot['pc11_d_id'].nunique())
print("Null pc11_d_id:", df_pivot['pc11_d_id'].isnull().sum())

# Find which pc11_d_id values appear more than once
duplicated = df_pivot[df_pivot.duplicated(subset=['pc11_d_id'], keep=False)]
print(duplicated[['State', 'District_Name', 'pc11_d_id']].sort_values('pc11_d_id'))

# Build lookup using BOTH state code + district name for uniqueness
name_to_pc11 = {}
for f in large_geojson['features']:
    props = f['properties']
    if props['d_name'] is not None and props['pc11_s_id'] is not None:
        key = (int(props['pc11_s_id']), props['d_name'])
        name_to_pc11[key] = props['pc11_d_id']

# Map to df_pivot using State_Code + District_Name
df_pivot['pc11_d_id'] = df_pivot.apply(
    lambda row: name_to_pc11.get((int(row['State_Code']), row['District_Name']), None),
    axis=1
)

print("Missing pc11_d_id:", df_pivot['pc11_d_id'].isnull().sum())
print("Unique pc11_d_id:", df_pivot['pc11_d_id'].nunique())

# Check the duplicates are fixed
print("\nBilaspur:")
print(df_pivot[df_pivot['District_Name'] == 'Bilaspur'][['State', 'District_Name', 'pc11_d_id']])

from google.colab import files

df_pivot.to_csv('df_pivot.csv', index=False)
files.download('df_pivot.csv')

fig = px.choropleth_mapbox(
    df_pivot,
    geojson=large_geojson,
    featureidkey='properties.pc11_d_id',
    locations='pc11_d_id',
    color='Literacy_Rate',
    color_continuous_scale='Viridis',
    range_color=[30, 100],
    title='Literacy Rate by District - Census 2011',
    hover_data=['State', 'District_Name', 'Total_Pop', 'Literacy_Rate'],
    mapbox_style='carto-positron',
    center={"lat": 20.5937, "lon": 78.9629},
    zoom=3.5,
    opacity=0.7
)
fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=600
)
fig.show()

#!pip install topojson

import topojson
import json
import os

topo = topojson.Topology(large_geojson, prequantize=False)
compressed = topo.togeojson(simplify=0.001)  # start with 0.001, adjust if needed

with open('india_compressed.geojson', 'w') as f:
    json.dump(compressed, f)

size = os.path.getsize('india_compressed.geojson') / (1024*1024)
print(f"Compressed size: {size:.1f} MB")

print(dir(topo))

import topojson
import json
import os

# Simplify first then convert
topo = topojson.Topology(large_geojson, prequantize=False)
topo_simplified = topo.toposimplify(0.001)
compressed = topo_simplified.to_geojson()

with open('india_compressed.geojson', 'w') as f:
    f.write(compressed)

size = os.path.getsize('india_compressed.geojson') / (1024*1024)
print(f"Compressed size: {size:.1f} MB")

# Load compressed geojson
with open('india_compressed.geojson', 'r') as f:
    compressed_geojson = json.load(f)

# Check properties are still intact
print(compressed_geojson['features'][0]['properties'])
print("Total features:", len(compressed_geojson['features']))

fig = px.choropleth_mapbox(
    df_pivot,
    geojson=compressed_geojson,
    featureidkey='properties.pc11_d_id',
    locations='pc11_d_id',
    color='Literacy_Rate',
    color_continuous_scale='Viridis',
    range_color=[30, 100],
    title='Literacy Rate by District - Census 2011',
    hover_data=['State', 'District_Name', 'Total_Pop', 'Literacy_Rate'],
    mapbox_style='carto-positron',
    center={"lat": 20.5937, "lon": 78.9629},
    zoom=3.5,
    opacity=0.7
)
fig.update_layout(
    margin={"r":0, "t":40, "l":0, "b":0},
    height=600
)
fig.show()

from google.colab import files
files.download('india_compressed.geojson')